"use client";

import { useLayoutEffect, useRef } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

const BASE_PATH = process.env.NODE_ENV === "production" ? "/CNSRC" : "";
const ASSETS = { immersive:`${BASE_PATH}/images/immersive-space.png`, production:`${BASE_PATH}/images/production-stage.png`, spatial:`${BASE_PATH}/images/spatial-lab.png`, strategy:`${BASE_PATH}/images/b2w-strategy.png`, live:`${BASE_PATH}/images/monarca-live.png`, immersiveLab:`${BASE_PATH}/images/brown-immersive.png`, deployment:`${BASE_PATH}/images/tridifect-deploy.png` };
function KineticText({children,className="",label}:{children:string;className?:string;label?:string}){return <span className={`kinetic-text ${className}`} aria-label={label??children}>{children.split(" ").map((word,wi,words)=><span className="word-unit" aria-hidden="true" key={`${word}-${wi}`}>{Array.from(word).map((c,ci)=><span className="char-wrap" key={`${c}-${ci}`}><span className="char">{c}</span></span>)}{wi<words.length-1&&<span className="word-space"> </span>}</span>)}</span>}
const companies=[{index:"01",name:"B2W AGENCY",role:"ESTRATEGIA, COMUNICACIÓN Y MARKETING",description:"B2W define objetivos, audiencias, posicionamiento, comunicación, campañas, medios, marketing digital y performance.",terms:"STRATEGY / BRAND / AUDIENCES / MEDIA / MARKETING / PERFORMANCE",image:ASSETS.strategy,position:"center 62%"},{index:"02",name:"MONARCA MEDIA",role:"PRODUCCIÓN, CONTENIDO Y EVENTOS",description:"Producción audiovisual, fotografía, documental, spots, motion graphics, streaming, multicámara, eventos, BTL y producción ejecutiva.",terms:"FILM / CONTENT / EVENTS / PRODUCTION / STREAMING / BTL",image:ASSETS.live,position:"center center"},{index:"03",name:"DOCTOR BROWN LABS",role:"EXPERIENCIAS, MEDIOS INMERSIVOS Y TECNOLOGÍA",description:"Diseño de experiencias, videomapping, fulldome, multiproyección, instalaciones interactivas, XR, spatial computing, web 3D, reconstrucción 3D/4D, gemelos digitales, software, IA, agentes, computer vision, sensores y tracking.",terms:"IMMERSIVE / INTERACTIVE / XR / SPATIAL / 3D / 4D / AI / SOFTWARE",image:ASSETS.immersiveLab,position:"center center",rich:true},{index:"04",name:"TRIDIFECT",role:"HARDWARE E INFRAESTRUCTURA",description:"LED, proyección, pantallas táctiles, displays, tótems, sistemas holográficos, integración, montaje y despliegue.",terms:"LED / PROJECTION / DISPLAYS / TOUCH / HARDWARE / DEPLOYMENT",image:ASSETS.deployment,position:"center center"}];
const combinations=["CAMPAÑA + CONTENIDO + ACTIVACIÓN + EXPERIENCIA DIGITAL","NARRATIVA + PRODUCCIÓN + MAPPING + INTERACCIÓN + SOFTWARE","EVENTO + AUDIOVISUAL + LED + EXPERIENCIA INTERACTIVA","COMUNICACIÓN + 3D + GEMELO DIGITAL + WEB + EXPERIENCIA PRESENCIAL"];
const totalCapabilities=["COMUNICACIÓN Y CAMPAÑAS","PRODUCCIÓN AUDIOVISUAL","EVENTOS Y ACTIVACIONES","EXPERIENCIAS INMERSIVAS","ESPACIOS Y EXPERIENCIAS DIGITALES","INTELIGENCIA Y SISTEMAS","INFRAESTRUCTURA TECNOLÓGICA"];
const cases=[{number:"01",title:"SISTEMAS QUE CONECTAN NARRATIVA Y ESPACIO",tags:"ESTRATEGIA / CONTENIDO / EXPERIENCIA",image:ASSETS.immersive},{number:"02",title:"PRODUCCIÓN QUE SE CONVIERTE EN EXPERIENCIA",tags:"FILM / EVENTO / TECNOLOGÍA",image:ASSETS.production},{number:"03",title:"LO FÍSICO Y LO DIGITAL EN UN MISMO SISTEMA",tags:"SPATIAL / 3D / SOFTWARE / HARDWARE",image:ASSETS.spatial}];

export default function Home(){const root=useRef<HTMLElement>(null);useLayoutEffect(()=>{gsap.registerPlugin(ScrollTrigger);if(!root.current||window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;const context=gsap.context(()=>{
ScrollTrigger.create({trigger:root.current,start:"top top",end:"bottom bottom",onUpdate:({progress})=>{root.current?.style.setProperty("--global-progress",progress.toFixed(4));root.current?.style.setProperty("--grid-shift",`${progress*96}px`)}});
const hero=root.current?.querySelector<HTMLElement>(".hero");if(hero){const rows=gsap.utils.toArray<HTMLElement>(hero.querySelectorAll(".hero-word"));const tl=gsap.timeline({scrollTrigger:{trigger:hero,start:"top top",end:"bottom bottom",scrub:1}});rows.forEach((row,i)=>{const chars=row.querySelectorAll(".char"),beat=i*1.2;tl.fromTo(chars,{rotateX:i===0?-20:(i%2?86:-86),rotateY:i%2?-18:18,scaleY:i===0?.86:.15,opacity:i===0?.72:.06},{rotateX:0,rotateY:0,scaleY:1,opacity:1,duration:.56,stagger:{each:.022,from:i===2?"center":"start"},ease:"power3.out"},beat);if(i<rows.length-1)tl.to(chars,{rotateX:78,scaleY:.22,opacity:.04,duration:.38,stagger:{each:.009,from:"edges"},ease:"power2.in"},beat+.7)});tl.fromTo(".hero-deck",{clipPath:"inset(0 100% 0 0)"},{clipPath:"inset(0 0% 0 0)",duration:.7},5.25).fromTo(".hero-rule",{scaleX:0},{scaleX:1,duration:1.2,ease:"none"},0)}
gsap.utils.toArray<HTMLElement>("[data-kinetic]").forEach((section,i)=>{const chars=section.querySelectorAll(".char"),bands=section.querySelectorAll(".media-band"),rails=section.querySelectorAll(".term-rail");const tl=gsap.timeline({scrollTrigger:{trigger:section,start:"top top",end:"bottom bottom",scrub:1}});tl.fromTo(chars,{rotateY:i%2?88:-88,scaleX:.2,opacity:.12},{rotateY:0,scaleX:1,opacity:1,stagger:{each:.012,from:i%3===0?"center":"start"},duration:.8,ease:"power3.out"},0);if(bands.length){tl.fromTo(bands,{clipPath:"inset(0 50% 0 50%)",z:-180,filter:"grayscale(1) contrast(1.25)"},{clipPath:"inset(0 0% 0 0%)",z:0,filter:"grayscale(.2) contrast(1.08)",stagger:.08,duration:1.1,ease:"power2.inOut"},.08);tl.to(bands,{clipPath:"inset(48% 0 48% 0)",z:120,stagger:{each:.05,from:"edges"},duration:.75},1.55)}if(rails.length)tl.fromTo(rails,{"--rail-scale":0},{"--rail-scale":1,duration:1.2,ease:"none"},.1);tl.to(chars,{rotateX:-78,scaleY:.18,opacity:.1,stagger:{each:.008,from:"edges"},duration:.65,ease:"power2.in"},1.62)});
const conv=root.current?.querySelector<HTMLElement>(".convergence-intro");if(conv){const chars=conv.querySelectorAll(".char"),tl=gsap.timeline({scrollTrigger:{trigger:conv,start:"top 48%",end:"bottom 8%",scrub:1}});tl.fromTo(chars,{rotateY:-88,scaleX:.2,opacity:.12},{rotateY:0,scaleX:1,opacity:1,stagger:{each:.012,from:"center"},duration:.8,ease:"power3.out"},.28);tl.to(chars,{rotateX:-78,scaleY:.18,opacity:.1,stagger:{each:.008,from:"edges"},duration:.65,ease:"power2.in"},1.62)}
gsap.utils.toArray<HTMLElement>(".combo-line").forEach((line,i)=>gsap.fromTo(line.querySelectorAll(".char"),{rotateX:88,scaleY:.1,opacity:.08},{rotateX:0,scaleY:1,opacity:1,stagger:{each:.01,from:i%2?"edges":"center"},scrollTrigger:{trigger:line,start:"top 82%",end:"center 48%",scrub:.8}}));
gsap.utils.toArray<HTMLElement>(".capability-line").forEach((line,i)=>gsap.fromTo(line.querySelectorAll(".char"),{rotateY:i%2?84:-84,opacity:.08,scaleX:.15},{rotateY:0,opacity:1,scaleX:1,stagger:{each:.008,from:"center"},scrollTrigger:{trigger:line,start:"top 78%",end:"center 46%",scrub:true}}));
const casesHead=root.current?.querySelector<HTMLElement>(".cases-head");if(casesHead){const title=casesHead.querySelector<HTMLElement>("h2");if(title)gsap.fromTo(title.querySelectorAll(".char"),{rotateY:-88,scaleX:.18,opacity:.08},{rotateY:0,scaleX:1,opacity:1,stagger:{each:.025,from:"center"},ease:"power3.out",scrollTrigger:{trigger:title,start:"top 82%",end:"top 42%",scrub:.9}})}

gsap.utils.toArray<HTMLElement>(".case").forEach((scene,index)=>{
  const title=scene.querySelector<HTMLElement>("h3");
  const meta=scene.querySelector<HTMLElement>(".case-meta");
  const frames=scene.querySelectorAll<HTMLElement>(".case-frame");
  const images=scene.querySelectorAll<HTMLElement>(".case-frame img");
  if(!title||!frames.length)return;
  const chars=title.querySelectorAll(".char");
  const tl=gsap.timeline({scrollTrigger:{trigger:scene,start:"top top",end:"bottom bottom",scrub:1}});
  gsap.set(frames,{transformOrigin:"50% 50%",transformPerspective:1000});
  gsap.set(images,{transformOrigin:"50% 50%"});

  if(index===0){
    const openMasks=["inset(8% 47% 8% 47%)","inset(45% 8% 45% 8%)","inset(45% 8% 45% 8%)","inset(10% 46% 10% 46%)","inset(6% 46% 6% 46%)"];
    const openZ=[-260,-120,-210,-160,-300],openX=[-8,2,4,-3,8],openY=[2,-7,7,-2,3],openRY=[-10,5,-5,7,-8];
    tl.fromTo(frames,{clipPath:(i)=>openMasks[i],z:(i)=>openZ[i],xPercent:(i)=>openX[i],yPercent:(i)=>openY[i],rotateY:(i)=>openRY[i],filter:"grayscale(1) contrast(1.3)"},{clipPath:"inset(0% 0% 0% 0%)",z:0,xPercent:0,yPercent:0,rotateY:0,filter:"grayscale(.25) contrast(1.08)",stagger:{each:.09,from:"center"},duration:1.08,ease:"power2.inOut"},0)
      .fromTo(images,{scale:1.1},{scale:1,stagger:{each:.055,from:"center"},duration:1.05,ease:"power2.out"},.03)
      .fromTo(chars,{rotateY:-88,scaleX:.18,opacity:.08},{rotateY:0,scaleX:1,opacity:1,stagger:{each:.012,from:"center"},duration:.86,ease:"power3.out"},.34);
    if(meta)tl.fromTo(meta,{clipPath:"inset(0 100% 0 0)",opacity:.12},{clipPath:"inset(0 0% 0 0)",opacity:1,duration:.5,ease:"power2.out"},.22);
    tl.to(frames,{clipPath:(i)=>i%2?"inset(46% 0 46% 0)":"inset(0 47% 0 47%)",z:(i)=>[140,210,120,190,250][i],rotateX:(i)=>i%2?-7:5,stagger:{each:.06,from:"edges"},duration:.72,ease:"power2.in"},1.72)
      .to(chars,{rotateX:-78,scaleY:.18,opacity:.08,stagger:{each:.008,from:"edges"},duration:.62,ease:"power2.in"},1.78);
    if(meta)tl.to(meta,{clipPath:"inset(0 0 0 100%)",opacity:.08,duration:.42,ease:"power2.in"},1.76);
  }else if(index===1){
    const openMasks=["inset(48% 0 48% 0)","inset(0 100% 0 0)","inset(100% 0 0 0)","inset(0 0 0 100%)","inset(48% 0 48% 0)"];
    const openZ=[-150,-280,-110,-230,-170],openX=[-4,-8,2,9,4],openY=[-8,2,9,-3,8],openRX=[7,0,-8,0,6];
    tl.fromTo(frames,{clipPath:(i)=>openMasks[i],z:(i)=>openZ[i],xPercent:(i)=>openX[i],yPercent:(i)=>openY[i],rotateX:(i)=>openRX[i],filter:"grayscale(1) contrast(1.28)"},{clipPath:"inset(0% 0% 0% 0%)",z:0,xPercent:0,yPercent:0,rotateX:0,filter:"grayscale(.25) contrast(1.08)",stagger:{each:.08,from:"edges"},duration:1.14,ease:"power3.inOut"},0)
      .fromTo(images,{scale:1.12,yPercent:(i)=>i%2?4:-3},{scale:1,yPercent:0,stagger:{each:.05,from:"edges"},duration:1.08,ease:"power2.out"},.02)
      .fromTo(chars,{rotateX:84,scaleY:.16,opacity:.08},{rotateX:0,scaleY:1,opacity:1,stagger:{each:.011,from:"edges"},duration:.88,ease:"power3.out"},.38);
    if(meta)tl.fromTo(meta,{clipPath:"inset(100% 0 0 0)",opacity:.1},{clipPath:"inset(0% 0 0 0)",opacity:1,duration:.52,ease:"power2.out"},.2);
    tl.to(frames,{clipPath:(i)=>["inset(0 0 100% 0)","inset(0 0 0 100%)","inset(0 100% 0 0)","inset(100% 0 0 0)","inset(0 0 100% 0)"][i],z:(i)=>[170,250,130,220,180][i],xPercent:(i)=>[-4,-8,6,8,3][i],rotateY:(i)=>[-5,7,-5,6,-4][i],stagger:{each:.055,from:"center"},duration:.76,ease:"power2.in"},1.74)
      .to(chars,{rotateY:76,scaleX:.2,opacity:.08,stagger:{each:.008,from:"center"},duration:.6,ease:"power2.in"},1.82);
    if(meta)tl.to(meta,{clipPath:"inset(0 100% 0 0)",opacity:.08,duration:.42,ease:"power2.in"},1.77);
  }else{
    const openMasks=["inset(0 0 100% 0)","inset(0 47% 0 47%)","inset(100% 0 0 0)","inset(0 100% 0 0)","inset(0 0 0 100%)"];
    const openZ=[-210,-320,-140,-260,-190],openX=[-7,0,6,-8,9],openY=[7,0,-7,4,4],openRY=[-8,0,7,-9,9];
    tl.fromTo(frames,{clipPath:(i)=>openMasks[i],z:(i)=>openZ[i],xPercent:(i)=>openX[i],yPercent:(i)=>openY[i],rotateY:(i)=>openRY[i],filter:"grayscale(1) contrast(1.32)"},{clipPath:"inset(0% 0% 0% 0%)",z:0,xPercent:0,yPercent:0,rotateY:0,filter:"grayscale(.25) contrast(1.08)",stagger:{each:.085,from:"end"},duration:1.12,ease:"power2.inOut"},0)
      .fromTo(images,{scale:1.11,xPercent:(i)=>[-3,0,4,-4,4][i]},{scale:1,xPercent:0,stagger:{each:.055,from:"end"},duration:1.08,ease:"power2.out"},.04)
      .fromTo(chars,{rotateY:88,scaleX:.18,opacity:.08},{rotateY:0,scaleX:1,opacity:1,stagger:{each:.012,from:"end"},duration:.9,ease:"power3.out"},.36);
    if(meta)tl.fromTo(meta,{clipPath:"inset(0 0 0 100%)",opacity:.1},{clipPath:"inset(0 0 0 0%)",opacity:1,duration:.5,ease:"power2.out"},.24);
    tl.to(frames,{clipPath:(i)=>["inset(47% 0 47% 0)","inset(0 46% 0 46%)","inset(0 0 100% 0)","inset(0 0 0 100%)","inset(0 100% 0 0)"][i],z:(i)=>[230,150,270,180,220][i],yPercent:(i)=>[5,-3,-8,4,4][i],rotateX:(i)=>[6,-5,8,-6,6][i],stagger:{each:.06,from:"end"},duration:.74,ease:"power2.in"},1.73)
      .to(chars,{rotateX:-82,scaleY:.16,opacity:.07,stagger:{each:.008,from:"edges"},duration:.62,ease:"power2.in"},1.8);
    if(meta)tl.to(meta,{clipPath:"inset(100% 0 0 0)",opacity:.07,duration:.42,ease:"power2.in"},1.77);
  }
});
},root);return()=>context.revert()},[]);
return <main ref={root} className="site-shell"><div className="procedural-grid" aria-hidden="true"><i/><i/><i/><i/><i/><i/></div><header className="site-header"><a href="#top" className="brand-mark" aria-label="Inicio">CNSRC<span>™</span></a><div className="header-axis" aria-hidden="true"><span/></div><a href="#contacto" className="header-link">HABLEMOS <span>↘</span></a></header>
<section id="top" className="hero scene-dark"><div className="hero-stage"><div className="scene-index">CAPACIDAD INTEGRADA <span>00—05</span></div><div className="hero-sequence" aria-label="Estrategia. Producción. Experiencias. Tecnología. Infraestructura.">{["ESTRATEGIA.","PRODUCCIÓN.","EXPERIENCIAS.","TECNOLOGÍA.","INFRAESTRUCTURA."].map(word=><div className="hero-word" key={word}><KineticText>{word}</KineticText></div>)}</div><div className="hero-bottom"><p className="hero-deck">Cuatro empresas especializadas integran sus capacidades para desarrollar proyectos completos, desde la estrategia hasta la implementación.</p><div className="scroll-cue">SCROLL / TIMELINE <span>↓</span></div></div><div className="hero-rule" aria-hidden="true"/></div></section>
<section className="sum-scene kinetic-scene" data-kinetic><div className="sticky-stage sum-stage"><div className="scene-index dark-index">SISTEMA CONJUNTO <span>01—04</span></div><h2 className="sum-title"><KineticText>UNA ESTRUCTURA MÁS GRANDE QUE LA SUMA DE SUS PARTES.</KineticText></h2><div className="company-weave" aria-label="B2W Agency, Monarca Media, Doctor Brown Labs y Tridifect"><span>B2W AGENCY</span><span>MONARCA MEDIA</span><span>DOCTOR BROWN LABS</span><span>TRIDIFECT</span></div><div className="weave-lines" aria-hidden="true"><i/><i/><i/><i/></div></div></section>
<section className="company-flow scene-dark">{companies.map(c=><article className={`company-scene kinetic-scene ${c.rich?"is-rich":""}`} data-kinetic key={c.name}><div className="sticky-stage company-stage"><div className="company-media" aria-hidden="true">{[0,1,2,3,4].map(b=><div className={`media-band band-${b+1}`} key={b}><img src={c.image} alt="" style={{objectPosition:c.position}}/></div>)}</div><div className="scene-index">CORRIENTE {c.index} <span>{c.index}—04</span></div><h2 className="company-name"><KineticText>{c.name}</KineticText></h2><div className="company-copy"><h3>{c.role}</h3><p>{c.description}</p></div><div className="term-rail"><span>{c.terms}</span><span aria-hidden="true">{c.terms}</span></div></div></article>)}</section>
<section className="convergence scene-light"><div className="convergence-intro"><div className="scene-index dark-index">CONVERGENCIA <span>04→01</span></div><h2><KineticText>JUNTAS, ESTAS CAPACIDADES PERMITEN HACER MUCHO MÁS.</KineticText></h2></div><div className="combinations">{combinations.map((line,i)=><div className="combo-line" key={line}><span className="combo-number">0{i+1}</span><KineticText>{line}</KineticText></div>)}</div></section>
<section className="total-capacity scene-dark"><div className="capacity-heading"><div className="scene-index">CAPACIDAD TOTAL <span>07 CAMPOS</span></div><p>UNA SOLA ESTRUCTURA / DE LA IDEA AL DESPLIEGUE</p></div><div className="capability-list">{totalCapabilities.map((cap,i)=><div className="capability-line" key={cap}><span className="cap-number">{String(i+1).padStart(2,"0")}</span><KineticText>{cap}</KineticText></div>)}</div></section>
<section className="cases scene-light" aria-labelledby="cases-title"><div className="cases-head"><div className="scene-index dark-index">CASOS / MARCOS ABIERTOS <span>03</span></div><h2 id="cases-title" style={{fontSize:"clamp(5rem, 15vw, 15rem)",lineHeight:.78,whiteSpace:"nowrap"}}><KineticText>PROYECTOS</KineticText></h2></div>{cases.map((p,i)=><article className={`case case-${i+1}`} key={p.number}><div className="sticky-stage case-stage"><div className="case-media" aria-hidden="true">{[0,1,2,3,4].map(f=><div className={`case-frame frame-${f+1}`} key={f}><img src={p.image} alt=""/></div>)}</div><div className="case-meta"><span>{p.number}</span><span>{p.tags}</span></div><h3><KineticText>{p.title}</KineticText></h3></div></article>)}</section>
<footer id="contacto" className="finale scene-light kinetic-scene" data-kinetic><div className="sticky-stage finale-stage"><div className="scene-index dark-index">SIGUIENTE PROYECTO <span>∞</span></div><h2><KineticText>DE LA ESTRATEGIA A LA IMPLEMENTACIÓN.</KineticText></h2><p className="finale-copy">Una estructura capaz de pensar, producir, desarrollar e implementar proyectos completos.</p><div className="finale-companies">B2W AGENCY · MONARCA MEDIA · DOCTOR BROWN LABS · TRIDIFECT</div><a className="contact-link" href="mailto:proyectos@cnsrc.com"><span>HABLEMOS DE TU PROYECTO</span><span aria-hidden="true">↗</span></a><div className="footer-line"><span>CNSRC / 2026</span><a href="#top">VOLVER ARRIBA ↑</a></div></div></footer></main>}
